### PR TITLE
Use `packageLicenseOverride` for `check-licenses`.

### LINKED ISSUE #35: `packageLicenseOverride` doesn't work when using `check-licenses` command
I have the following config: 

``` yaml
permittedLicenses:
  - Apache

packageLicenseOverride:
  rxdart: Apache
```

And a direct dependency on https://pub.dev/packages/rxdart

Expected output: 
` rxdart  Apache`

Actual output:
`rxdart unknown-license`

Current workaround:

Updating my config file with
```yaml
approvedPackages:
  unknown-license:
    - rxdart # https://github.com/ReactiveX/rxdart/blob/58c82c0eefcea76b131de0d445fa24467ae58c47/LICENSE
```

### PR DESCRIPTION
**Pull request by Jonas-Sander**
The `lic_ck check-licenses` command will now use the `packageLicenseOverride`.

Fixes #35

### CODE REVIEW

**Comment by Jonas-Sander** [comment]
@rufman Unfortunately the dart tests are not passing for me, could you check that they pass in your environment?

When running `dart test` on `trunk`:
```
00:01 +80 -19: Some tests failed.
```

On the PR branch:
```
00:01 +81 -20: Some tests failed.
```

Dart SDK version: 2.17.5 (stable)

**Comment by rufman** [comment]
If you rebase upsteam/trunk (or merge upsteam/trunk) into your PR the tests should pass

**Comment by Jonas-Sander** [comment]
The tests do still not pass for me locally (81 pass, 20 fail)

**Comment by Jonas-Sander** [comment]
Which Dart version do you use?

**Comment by rufman** [comment]
version 3.1.0

**Comment by Jonas-Sander** [comment]
Would this be good to merge for you?

**Review by rufman — APPROVED** [review]
I think applying the same pattern to other overrides would be good. But for another PR.

**Comment by Jonas-Sander** [comment]
grafik

You would need to merge this, I can't.

**Pull request merged**
